---

- hosts: all
  become: true
  roles:
    - common
    - sshd
    - iptables
    - oracle_jdk
    - rbenv
    - nginx
    - php_fpm
    - my_nginx_conf
    - mysql
    - wordpress
    - hubot
    - my_hubot
    - fluentd
    - elasticsearch
    - kibana
    - my_fek
    - asvie_unicorn
    - cpuminer
    - my_cpuminer
    - scala
    - pt_common
    - arib25
