---

- hosts: astail_net
  become: true
  roles:
    - common
    - sshd
    - iptables
    - oracle_jdk
    - nginx
    - php_fpm
    - letsencrypt
    - my_nginx_conf
    - mysql
    - wordpress
    - scala

- hosts: n2
  become: true
  roles:
    - common
    - iptables
    - sshd
    - oracle_jdk
    - rbenv
    - nginx
    - php_fpm
    - my_nginx_conf
    - mysql
    - scala
    - pt_common
    - arib25
    - pcscd
    - pt3driver
    - recpt1
    - nodejs
    - mirakurun

- hosts: aws
  become: true
  roles:
    - aws_common
#    - sshd
#    - iptables
#    - oracle_jdk
#    - nginx
#    - php_fpm
#    - letsencrypt
#    - my_nginx_conf
#    - mysql
#    - wordpress
#    - scala
