---

- hosts: all
  become: true
  roles:
    - common

- hosts: astail_net
  become: true
  roles:
    - sshd
    - iptables
    - oracle_jdk
    - rbenv
    - nginx
    - php_fpm
    - mysql
    - wordpress
    - my_nginx_conf
    - hubot
    - my_hubot

- hosts: astail_net
  become: true
  roles:
    - fluentd
    - elasticsearch
    - kibana
    - my_fek

- hosts: astail_net
  become: true
  roles:
    - asvie_unicorn
