---

- hosts: all
  become: true
  roles:
    - common

- hosts: astail_net
  become: true
  roles:
    - sshd
    - iptables
    - oracle_jdk
    - rbenv
    - nginx
    - php-fpm
    - mysql
    - wordpress
    - my_nginx_conf
    - hubot
    - my_hubot
    - fluentd
