---

- hosts: astail_net
  become: true
  roles:
    - common
    - sshd
    - iptables
    - oracle_jdk
    - rbenv
    - nginx
    - php_fpm
    - my_nginx_conf
    - mysql
    - wordpress
    - cpuminer
    - my_cpuminer
    - scala

- hosts: n2
  become: true
  roles:
    - common
    - iptables
    - sshd
    - oracle_jdk
    - rbenv
    - nginx
    - php_fpm
    - my_nginx_conf
    - mysql
    - scala
    - pt_common
    - arib25
    - pcscd
