#!/bin/sh

export HUBOT_SLACK_TOKEN={{ HUBOT_SLACK_TOKEN }}

set -e

npm install
export PATH="node_modules/.bin:node_modules/hubot/node_modules/.bin:$PATH"

forever start -c coffee node_modules/.bin/hubot --adapter \slack
