---

version: 2
jobs:
  build:
    working_directory: ~/ansible_astail
    docker:
      - image: astail/ansible-ci-base
    steps:
      - checkout
      - run: ansible --version
      - run: echo "${ANSIBLE_VAULT_PASS}" > ansible_vault.txt
      - run:
         name: create all.yml
         command: |
           echo "
           - hosts: all
             become: true
             roles:" >> all.yml
           ls roles | sed "s/^/    - /g" >> all.yml
      - run: ansible-lint all.yml
      - run: ansible-playbook -i "localhost," all.yml --syntax-check --vault-password-file ansible_vault.txt
