---

- name: install nodejs npm
  yum:
    name: "{{ item }}"
    enablerepo: epel
  with_items:
    - nodejs
    - npm

- name: check node install
  command: node -v
  register: node
  changed_when: node.rc == 1
  failed_when: node == 1

- name: npm install n
  npm:
    name: n
    global: yes
  when: node.stdout.find('{{ node_version }}') == -1

- name: n {{ node_version }}
  shell: "n {{ node_version }}"
  tags: skip_ansible_lint
  when: node.stdout.find('{{ node_version }}') == -1

- name: ln -s /usr/local/bin/node /bin/node
  file:
    src: /usr/local/bin/node
    dest: /bin/node
    state: link
    force: yes

- name: ln -s /usr/local/bin/npm /bin/npm
  file:
    src: /usr/local/bin/npm
    dest: /bin/npm
    state: link
    force: yes
