---

tmp: /tmp
ssh_user: astel
ruby_version: 2.4.1
scala_version: 2.11.8

db_root_user_password: "{{ vault_db_root_user_password }}"

wordpress_version: 4.7.4

HUBOT_SLACK_TOKEN: "{{ vault_HUBOT_SLACK_TOKEN }}"

domain: astail.net
letsencrypt_mail: "{{ vault_letsencrypt_mail }}"

rsync_allow_ip: "{{ vault_rsync_allow_ip }}"
