---

- name: copy nginx.conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: restart nginx service

- name: copy log_format.conf
  copy:
    src: log_format.conf
    dest: /etc/nginx/log_format.conf
  notify: restart nginx service

- name: copy {{ server_group_name }}.conf
  template:
    src: "{{ server_group_name }}.conf.{{ astel_env }}"
    dest: /etc/nginx/conf.d/{{ server_group_name }}.conf
  notify: restart nginx service

- name: mkdir /var/log/nginx/{{ server_group_name }}
  file:
    path: "/var/log/nginx/{{ server_group_name }}"
    state: directory
    owner: nginx
    group: nginx

- name: delete default.conf
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify: restart nginx service

- name: mkdir {{ web_root }}
  file:
    path: "{{ web_root }}"
    owner: nginx
    group: wheel
    state: directory

- name: start nginx service
  systemd:
    name: nginx
    state: started
    enabled: yes
