---

- name: wget jdk-{{ version }}-linux-x64.rpm
  get_url:
    url: "{{ url }}"
    dest: "/usr/local/src/jdk-{{ version }}-linux-x64.rpm"
    headers: "Cookie:' gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'"
    validate_certs: no
    owner: root
    group: root
    mode: 744

- name: install jdk-{{ version }}-linux-x64.rpm
  yum:
    name: "/usr/local/src/jdk-{{ version }}-linux-x64.rpm"
    state: present
