---

- name: wget elasticsearch.rpm
  get_url:
    url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.4.0.rpm
    dest: "{{ tmp }}/elasticsearch-5.4.0.rpm"

- name: yum install elasticsearch
  yum:
    name: "{{ tmp }}/elasticsearch-5.4.0.rpm"

- name: fix ES_JAVA_OPTS
  lineinfile:
    dest: /etc/sysconfig/elasticsearch
    regexp: "^#ES_JAVA_OPTS="
    line: 'ES_JAVA_OPTS="-Xms512m -Xmx512m"'
    backrefs: yes

- name: service elasticsearch start
  systemd:
    name: elasticsearch
    state: started
    enabled: yes
